server:
  port: 3777

spring:
  profiles:
    active: mongo
---

## jpa,등등 orm 제외
## (의존성 문제 생기면 먼저 보기)
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration